language: ruby
rvm:
- 2.3.0
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake ci:tests
services:
- postgresql
deploy:
  provider: heroku
  app: slow-food-august
  on:
    branch: deployment
  run:
  - rake db:migrate
  api_key:
    secure: Kw+lOhHMdIFw1nrll/CG7HIuJLHk1tT45p78nbj6R9iNuvmWBMbwiwmCwBSKxKzEDZSWkyKQQ9sqz2uVeRtyFDJXfwuqRjx5jo1H6Ks3kQFDio9BB3cBDSocD00fIHaMY2bAr12tLKkUvn83wFLcm7POGZCJqEfzqS2KDeJc3Qsma6TXaipzKr3RoNw4CtU5jYmD0WKa2RvqdsG91y/iGI0jOUWNBvmNmIiOw5+6b9nhxNcOp7wtZVRQs4ELKSAQrrsLMQi+sG3pT+T1V3Gsojv1s8LG+2hSqKT9KwsaIUOyJFmFLE97X4mIEx+LRTH9zaRtL6iYPNei0vff5oUoI1uTomG3FUnDFMYd0pkAGdiaxqK1sWKRooujvZCyLsht2lNCpJEWt7AkZQmFSLX6ZTuS6msf5ELr6shnV/feqGtFUxc+GKwcijsjmfHRkrMM87JAKgSaj3YheWO+qeitixvepPqkaaqlUzhcW54UhP6KKuHxYTGI//qe9932yWdFPnZz670au19e0Mk1Fu8vDkHKQTiYgoDm1xrvT+Vv/zE6EJdIHcXh3JgAhBfST3vnU+S+V1Th4LdBKYq6elageJ/rvs/M4rx6GXtHHTHLgaSpgsEW1injTx363N8zDwue7YzWbH0mEFpEMOiwoLvm7zl+TmYJH/WGnc22z6YilVs=
